<ref * 1 > Map(9) {
    'ZSjtXm8p_S0wywM1AAL8' => Socket {
        _events: [Object: null prototype] { },
        _eventsCount: 0,
            _maxListeners: undefined,
                nsp: Namespace {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    sockets: [Circular * 1],
                        _fns: [],
                            _ids: 0,
                                server: [Server],
                                    name: '/',
                                        adapter: [Adapter],
                                            [Symbol(kCapture)]: false
        },
        client: Client {
            sockets: [Map],
                nsps: [Map],
                    server: [Server],
                        conn: [Socket],
                            encoder: Encoder { },
            decoder: [Decoder],
                id: 'EHU8jLGA02ghl517AAJU',
                    onclose: [Function: bound onclose],
                        ondata: [Function: bound ondata],
                            onerror: [Function: bound onerror],
                                ondecoded: [Function: bound ondecoded],
                                    connectTimeout: undefined
        },
        data: { },
        acks: Map(0) { },
        fns: [],
            flags: { },
        server: Server {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    _nsps: [Map],
                        parentNsps: Map(0) { },
            _path: '/socket.io',
                clientPathRegex: /^\/socket\.io\/socket\.io(\.min|\.msgpack\.min)?\.js(\.map)?$/,
                    _connectTimeout: 45000,
                        _serveClient: true,
                            _parser: [Object],
                                encoder: Encoder { },
            _adapter: [class Adapter extends EventEmitter],
                sockets: [Namespace],
                    opts: { },
            eio: [Server],
                httpServer: [Server],
                    engine: [Server],
                        [Symbol(kCapture)]: false
        },
        adapter: Adapter {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    nsp: [Namespace],
                        rooms: [Map],
                            sids: [Map],
                                encoder: Encoder { },
            [Symbol(kCapture)]: false
        },
        id: 'ZSjtXm8p_S0wywM1AAL8',
            connected: true,
                disconnected: false,
                    handshake: {
            headers: [Object],
                time: 'Sat Jul 17 2021 10:42:30 GMT+0430 (Iran Daylight Time)',
                    address: '::1',
                        xdomain: false,
                            secure: false,
                                issued: 1626502350861,
                                    url: '/socket.io/?EIO=4&transport=polling&t=Ngp62mS',
                                        query: [Object: null prototype],
                                            auth: [Object]
        },
        [Symbol(kCapture)]: false
    },
    'jFBhiA55lRLsHAfoAAL9' => Socket {
        _events: [Object: null prototype] { },
        _eventsCount: 0,
            _maxListeners: undefined,
                nsp: Namespace {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    sockets: [Circular * 1],
                        _fns: [],
                            _ids: 0,
                                server: [Server],
                                    name: '/',
                                        adapter: [Adapter],
                                            [Symbol(kCapture)]: false
        },
        client: Client {
            sockets: [Map],
                nsps: [Map],
                    server: [Server],
                        conn: [Socket],
                            encoder: Encoder { },
            decoder: [Decoder],
                id: 'XIGG8jtw4duAsweXAAJV',
                    onclose: [Function: bound onclose],
                        ondata: [Function: bound ondata],
                            onerror: [Function: bound onerror],
                                ondecoded: [Function: bound ondecoded],
                                    connectTimeout: undefined
        },
        data: { },
        acks: Map(0) { },
        fns: [],
            flags: { },
        server: Server {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    _nsps: [Map],
                        parentNsps: Map(0) { },
            _path: '/socket.io',
                clientPathRegex: /^\/socket\.io\/socket\.io(\.min|\.msgpack\.min)?\.js(\.map)?$/,
                    _connectTimeout: 45000,
                        _serveClient: true,
                            _parser: [Object],
                                encoder: Encoder { },
            _adapter: [class Adapter extends EventEmitter],
                sockets: [Namespace],
                    opts: { },
            eio: [Server],
                httpServer: [Server],
                    engine: [Server],
                        [Symbol(kCapture)]: false
        },
        adapter: Adapter {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    nsp: [Namespace],
                        rooms: [Map],
                            sids: [Map],
                                encoder: Encoder { },
            [Symbol(kCapture)]: false
        },
        id: 'jFBhiA55lRLsHAfoAAL9',
            connected: true,
                disconnected: false,
                    handshake: {
            headers: [Object],
                time: 'Sat Jul 17 2021 10:42:30 GMT+0430 (Iran Daylight Time)',
                    address: '::1',
                        xdomain: false,
                            secure: false,
                                issued: 1626502350862,
                                    url: '/socket.io/?EIO=4&transport=polling&t=Ngp630K',
                                        query: [Object: null prototype],
                                            auth: [Object]
        },
        [Symbol(kCapture)]: false
    },
    'oWE36PuSfUIOi2_qAAL-' => Socket {
        _events: [Object: null prototype] { },
        _eventsCount: 0,
            _maxListeners: undefined,
                nsp: Namespace {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    sockets: [Circular * 1],
                        _fns: [],
                            _ids: 0,
                                server: [Server],
                                    name: '/',
                                        adapter: [Adapter],
                                            [Symbol(kCapture)]: false
        },
        client: Client {
            sockets: [Map],
                nsps: [Map],
                    server: [Server],
                        conn: [Socket],
                            encoder: Encoder { },
            decoder: [Decoder],
                id: 'dLq879MoCq0bMJ9PAAJW',
                    onclose: [Function: bound onclose],
                        ondata: [Function: bound ondata],
                            onerror: [Function: bound onerror],
                                ondecoded: [Function: bound ondecoded],
                                    connectTimeout: undefined
        },
        data: { },
        acks: Map(0) { },
        fns: [],
            flags: { },
        server: Server {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    _nsps: [Map],
                        parentNsps: Map(0) { },
            _path: '/socket.io',
                clientPathRegex: /^\/socket\.io\/socket\.io(\.min|\.msgpack\.min)?\.js(\.map)?$/,
                    _connectTimeout: 45000,
                        _serveClient: true,
                            _parser: [Object],
                                encoder: Encoder { },
            _adapter: [class Adapter extends EventEmitter],
                sockets: [Namespace],
                    opts: { },
            eio: [Server],
                httpServer: [Server],
                    engine: [Server],
                        [Symbol(kCapture)]: false
        },
        adapter: Adapter {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    nsp: [Namespace],
                        rooms: [Map],
                            sids: [Map],
                                encoder: Encoder { },
            [Symbol(kCapture)]: false
        },
        id: 'oWE36PuSfUIOi2_qAAL-',
            connected: true,
                disconnected: false,
                    handshake: {
            headers: [Object],
                time: 'Sat Jul 17 2021 10:42:30 GMT+0430 (Iran Daylight Time)',
                    address: '::1',
                        xdomain: false,
                            secure: false,
                                issued: 1626502350863,
                                    url: '/socket.io/?EIO=4&transport=polling&t=Ngp633h',
                                        query: [Object: null prototype],
                                            auth: [Object]
        },
        [Symbol(kCapture)]: false
    },
    'OLvcHLzJB5aZxgG6AAMD' => Socket {
        _events: [Object: null prototype] { },
        _eventsCount: 0,
            _maxListeners: undefined,
                nsp: Namespace {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    sockets: [Circular * 1],
                        _fns: [],
                            _ids: 0,
                                server: [Server],
                                    name: '/',
                                        adapter: [Adapter],
                                            [Symbol(kCapture)]: false
        },
        client: Client {
            sockets: [Map],
                nsps: [Map],
                    server: [Server],
                        conn: [Socket],
                            encoder: Encoder { },
            decoder: [Decoder],
                id: 'wicNYNZWbh07n89XAAJX',
                    onclose: [Function: bound onclose],
                        ondata: [Function: bound ondata],
                            onerror: [Function: bound onerror],
                                ondecoded: [Function: bound ondecoded],
                                    connectTimeout: undefined
        },
        data: { },
        acks: Map(0) { },
        fns: [],
            flags: { },
        server: Server {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    _nsps: [Map],
                        parentNsps: Map(0) { },
            _path: '/socket.io',
                clientPathRegex: /^\/socket\.io\/socket\.io(\.min|\.msgpack\.min)?\.js(\.map)?$/,
                    _connectTimeout: 45000,
                        _serveClient: true,
                            _parser: [Object],
                                encoder: Encoder { },
            _adapter: [class Adapter extends EventEmitter],
                sockets: [Namespace],
                    opts: { },
            eio: [Server],
                httpServer: [Server],
                    engine: [Server],
                        [Symbol(kCapture)]: false
        },
        adapter: Adapter {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    nsp: [Namespace],
                        rooms: [Map],
                            sids: [Map],
                                encoder: Encoder { },
            [Symbol(kCapture)]: false
        },
        id: 'OLvcHLzJB5aZxgG6AAMD',
            connected: true,
                disconnected: false,
                    handshake: {
            headers: [Object],
                time: 'Sat Jul 17 2021 10:42:30 GMT+0430 (Iran Daylight Time)',
                    address: '::1',
                        xdomain: false,
                            secure: false,
                                issued: 1626502350870,
                                    url: '/socket.io/?EIO=4&transport=polling&t=Ngp63Ak',
                                        query: [Object: null prototype],
                                            auth: [Object]
        },
        [Symbol(kCapture)]: false
    },
    'CCPUlVgbrjyAKjRTAAME' => Socket {
        _events: [Object: null prototype] { },
        _eventsCount: 0,
            _maxListeners: undefined,
                nsp: Namespace {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    sockets: [Circular * 1],
                        _fns: [],
                            _ids: 0,
                                server: [Server],
                                    name: '/',
                                        adapter: [Adapter],
                                            [Symbol(kCapture)]: false
        },
        client: Client {
            sockets: [Map],
                nsps: [Map],
                    server: [Server],
                        conn: [Socket],
                            encoder: Encoder { },
            decoder: [Decoder],
                id: '7d1Qi-fua2GBOKYTAAJY',
                    onclose: [Function: bound onclose],
                        ondata: [Function: bound ondata],
                            onerror: [Function: bound onerror],
                                ondecoded: [Function: bound ondecoded],
                                    connectTimeout: undefined
        },
        data: { },
        acks: Map(0) { },
        fns: [],
            flags: { },
        server: Server {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    _nsps: [Map],
                        parentNsps: Map(0) { },
            _path: '/socket.io',
                clientPathRegex: /^\/socket\.io\/socket\.io(\.min|\.msgpack\.min)?\.js(\.map)?$/,
                    _connectTimeout: 45000,
                        _serveClient: true,
                            _parser: [Object],
                                encoder: Encoder { },
            _adapter: [class Adapter extends EventEmitter],
                sockets: [Namespace],
                    opts: { },
            eio: [Server],
                httpServer: [Server],
                    engine: [Server],
                        [Symbol(kCapture)]: false
        },
        adapter: Adapter {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    nsp: [Namespace],
                        rooms: [Map],
                            sids: [Map],
                                encoder: Encoder { },
            [Symbol(kCapture)]: false
        },
        id: 'CCPUlVgbrjyAKjRTAAME',
            connected: true,
                disconnected: false,
                    handshake: {
            headers: [Object],
                time: 'Sat Jul 17 2021 10:42:30 GMT+0430 (Iran Daylight Time)',
                    address: '::1',
                        xdomain: false,
                            secure: false,
                                issued: 1626502350871,
                                    url: '/socket.io/?EIO=4&transport=polling&t=Ngp63I1',
                                        query: [Object: null prototype],
                                            auth: [Object]
        },
        [Symbol(kCapture)]: false
    },
    '3XYaBALysj8oVDBkAAMF' => Socket {
        _events: [Object: null prototype] { },
        _eventsCount: 0,
            _maxListeners: undefined,
                nsp: Namespace {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    sockets: [Circular * 1],
                        _fns: [],
                            _ids: 0,
                                server: [Server],
                                    name: '/',
                                        adapter: [Adapter],
                                            [Symbol(kCapture)]: false
        },
        client: Client {
            sockets: [Map],
                nsps: [Map],
                    server: [Server],
                        conn: [Socket],
                            encoder: Encoder { },
            decoder: [Decoder],
                id: 'EU0eaE6R8AAtMm3NAAJZ',
                    onclose: [Function: bound onclose],
                        ondata: [Function: bound ondata],
                            onerror: [Function: bound onerror],
                                ondecoded: [Function: bound ondecoded],
                                    connectTimeout: undefined
        },
        data: { },
        acks: Map(0) { },
        fns: [],
            flags: { },
        server: Server {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    _nsps: [Map],
                        parentNsps: Map(0) { },
            _path: '/socket.io',
                clientPathRegex: /^\/socket\.io\/socket\.io(\.min|\.msgpack\.min)?\.js(\.map)?$/,
                    _connectTimeout: 45000,
                        _serveClient: true,
                            _parser: [Object],
                                encoder: Encoder { },
            _adapter: [class Adapter extends EventEmitter],
                sockets: [Namespace],
                    opts: { },
            eio: [Server],
                httpServer: [Server],
                    engine: [Server],
                        [Symbol(kCapture)]: false
        },
        adapter: Adapter {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    nsp: [Namespace],
                        rooms: [Map],
                            sids: [Map],
                                encoder: Encoder { },
            [Symbol(kCapture)]: false
        },
        id: '3XYaBALysj8oVDBkAAMF',
            connected: true,
                disconnected: false,
                    handshake: {
            headers: [Object],
                time: 'Sat Jul 17 2021 10:42:30 GMT+0430 (Iran Daylight Time)',
                    address: '::1',
                        xdomain: false,
                            secure: false,
                                issued: 1626502350878,
                                    url: '/socket.io/?EIO=4&transport=polling&t=Ngp63Kc',
                                        query: [Object: null prototype],
                                            auth: [Object]
        },
        [Symbol(kCapture)]: false
    },
    'azSHgWxc2HeZ-Pg7AAPF' => Socket {
        _events: [Object: null prototype] { },
        _eventsCount: 0,
            _maxListeners: undefined,
                nsp: Namespace {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    sockets: [Circular * 1],
                        _fns: [],
                            _ids: 0,
                                server: [Server],
                                    name: '/',
                                        adapter: [Adapter],
                                            [Symbol(kCapture)]: false
        },
        client: Client {
            sockets: [Map],
                nsps: [Map],
                    server: [Server],
                        conn: [Socket],
                            encoder: Encoder { },
            decoder: [Decoder],
                id: 'PPJZIlBMTonB7hcWAAPC',
                    onclose: [Function: bound onclose],
                        ondata: [Function: bound ondata],
                            onerror: [Function: bound onerror],
                                ondecoded: [Function: bound ondecoded],
                                    connectTimeout: undefined
        },
        data: { },
        acks: Map(0) { },
        fns: [],
            flags: { },
        server: Server {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    _nsps: [Map],
                        parentNsps: Map(0) { },
            _path: '/socket.io',
                clientPathRegex: /^\/socket\.io\/socket\.io(\.min|\.msgpack\.min)?\.js(\.map)?$/,
                    _connectTimeout: 45000,
                        _serveClient: true,
                            _parser: [Object],
                                encoder: Encoder { },
            _adapter: [class Adapter extends EventEmitter],
                sockets: [Namespace],
                    opts: { },
            eio: [Server],
                httpServer: [Server],
                    engine: [Server],
                        [Symbol(kCapture)]: false
        },
        adapter: Adapter {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    nsp: [Namespace],
                        rooms: [Map],
                            sids: [Map],
                                encoder: Encoder { },
            [Symbol(kCapture)]: false
        },
        id: 'azSHgWxc2HeZ-Pg7AAPF',
            connected: true,
                disconnected: false,
                    handshake: {
            headers: [Object],
                time: 'Sat Jul 17 2021 10:43:21 GMT+0430 (Iran Daylight Time)',
                    address: '::1',
                        xdomain: false,
                            secure: false,
                                issued: 1626502401188,
                                    url: '/socket.io/?EIO=4&transport=polling&t=Ngp65ag',
                                        query: [Object: null prototype],
                                            auth: [Object]
        },
        [Symbol(kCapture)]: false
    },
    'pwRFG52W6szdyeamAAPG' => Socket {
        _events: [Object: null prototype] { },
        _eventsCount: 0,
            _maxListeners: undefined,
                nsp: Namespace {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    sockets: [Circular * 1],
                        _fns: [],
                            _ids: 0,
                                server: [Server],
                                    name: '/',
                                        adapter: [Adapter],
                                            [Symbol(kCapture)]: false
        },
        client: Client {
            sockets: [Map],
                nsps: [Map],
                    server: [Server],
                        conn: [Socket],
                            encoder: Encoder { },
            decoder: [Decoder],
                id: 'JTPVAMs8EUtkUfxIAAPD',
                    onclose: [Function: bound onclose],
                        ondata: [Function: bound ondata],
                            onerror: [Function: bound onerror],
                                ondecoded: [Function: bound ondecoded],
                                    connectTimeout: undefined
        },
        data: { },
        acks: Map(0) { },
        fns: [],
            flags: { },
        server: Server {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    _nsps: [Map],
                        parentNsps: Map(0) { },
            _path: '/socket.io',
                clientPathRegex: /^\/socket\.io\/socket\.io(\.min|\.msgpack\.min)?\.js(\.map)?$/,
                    _connectTimeout: 45000,
                        _serveClient: true,
                            _parser: [Object],
                                encoder: Encoder { },
            _adapter: [class Adapter extends EventEmitter],
                sockets: [Namespace],
                    opts: { },
            eio: [Server],
                httpServer: [Server],
                    engine: [Server],
                        [Symbol(kCapture)]: false
        },
        adapter: Adapter {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    nsp: [Namespace],
                        rooms: [Map],
                            sids: [Map],
                                encoder: Encoder { },
            [Symbol(kCapture)]: false
        },
        id: 'pwRFG52W6szdyeamAAPG',
            connected: true,
                disconnected: false,
                    handshake: {
            headers: [Object],
                time: 'Sat Jul 17 2021 10:43:21 GMT+0430 (Iran Daylight Time)',
                    address: '::1',
                        xdomain: false,
                            secure: false,
                                issued: 1626502401188,
                                    url: '/socket.io/?EIO=4&transport=polling&t=Ngp65b9',
                                        query: [Object: null prototype],
                                            auth: [Object]
        },
        [Symbol(kCapture)]: false
    },
    '4SBMOtVLvHHx8agrAAPH' => Socket {
        _events: [Object: null prototype] { },
        _eventsCount: 0,
            _maxListeners: undefined,
                nsp: Namespace {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    sockets: [Circular * 1],
                        _fns: [],
                            _ids: 0,
                                server: [Server],
                                    name: '/',
                                        adapter: [Adapter],
                                            [Symbol(kCapture)]: false
        },
        client: Client {
            sockets: [Map],
                nsps: [Map],
                    server: [Server],
                        conn: [Socket],
                            encoder: Encoder { },
            decoder: [Decoder],
                id: 'm7caiQbcvW6nELW_AAPE',
                    onclose: [Function: bound onclose],
                        ondata: [Function: bound ondata],
                            onerror: [Function: bound onerror],
                                ondecoded: [Function: bound ondecoded],
                                    connectTimeout: undefined
        },
        data: { },
        acks: Map(0) { },
        fns: [],
            flags: { },
        server: Server {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    _nsps: [Map],
                        parentNsps: Map(0) { },
            _path: '/socket.io',
                clientPathRegex: /^\/socket\.io\/socket\.io(\.min|\.msgpack\.min)?\.js(\.map)?$/,
                    _connectTimeout: 45000,
                        _serveClient: true,
                            _parser: [Object],
                                encoder: Encoder { },
            _adapter: [class Adapter extends EventEmitter],
                sockets: [Namespace],
                    opts: { },
            eio: [Server],
                httpServer: [Server],
                    engine: [Server],
                        [Symbol(kCapture)]: false
        },
        adapter: Adapter {
            _events: [Object: null prototype] { },
            _eventsCount: 0,
                _maxListeners: undefined,
                    nsp: [Namespace],
                        rooms: [Map],
                            sids: [Map],
                                encoder: Encoder { },
            [Symbol(kCapture)]: false
        },
        id: '4SBMOtVLvHHx8agrAAPH',
            connected: true,
                disconnected: false,
                    handshake: {
            headers: [Object],
                time: 'Sat Jul 17 2021 10:43:21 GMT+0430 (Iran Daylight Time)',
                    address: '::1',
                        xdomain: false,
                            secure: false,
                                issued: 1626502401191,
                                    url: '/socket.io/?EIO=4&transport=polling&t=Ngp6A1l',
                                        query: [Object: null prototype],
                                            auth: [Object]
        },
        [Symbol(kCapture)]: false
    }
}

